language: objective-c
osx_image: xcode10.2
xcode_project: CaretCaster.xcodeproj
xcode_scheme: CaretCaster
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
 openssl aes-256-cbc -K $encrypted_a657021b4dd6_key -iv $encrypted_a657021b4dd6_iv -in Secret.swift.enc -out CaretCaster/Helpers/Secret.swift -d
#- pod install
## pod added later