language: objective-c
osx_image: xcode10.2
xcode_project: CaretCaster.xcodeproj
xcode_scheme: CaretCaster

before_install: 
  - openssl aes-256-cbc -K $encrypted_a657021b4dd6_key -iv $encrypted_a657021b4dd6_iv -in Secret.swift.enc -out CaretCaster/Helpers/Secret.swift -d

script: 
  - xcodebuild -scheme CaretCaster -project CaretCaster.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' build test

after_success: 
  - bash <(curl -s https://codecov.io/bash)